/**
 * Committed artifact parsers (models.json, quarantine.json, deprecated.json,
 * patches.json).
 *
 * These files are generated by this toolchain, but they still cross the
 * boundary as `unknown` so corruption or hand-editing is caught with an
 * actionable typed error instead of leaking `any` into reconciliation. Every
 * persisted timestamp must be a canonical finite ISO-8601 instant, every id
 * must be a safe canonical model id, and duplicate ids are rejected.
 */
import { isCanonicalIsoInstant, isRecord, isSafeModelId, isSafeText, isString, isUnknownArray } from "./guards.ts";
import { PROTOCOLS, QUARANTINE_REASON_CODES, QUARANTINE_SOURCES } from "./types.ts";
import { parseCatalogModel } from "./catalog-parse.ts";
import { parseBaseUrl } from "./urls.ts";
import { FOURTEEN_DAYS_MS } from "./constants.ts";
import type {
  Availability,
  BaseUrlPatch,
  CatalogModel,
  DeprecatedEntry,
  Patches,
  Protocol,
  QuarantineReasonCode,
  QuarantineRecord,
  QuarantineSource,
} from "./types.ts";

/** Malformed committed artifact (bad JSON or shape). */
export class StateFileParseError extends Error {
  readonly name = "StateFileParseError";
  constructor(what: string, reason: string) {
    super(`state artifact ${what} is malformed: ${reason}`);
  }
}

/** Parse JSON text and wrap syntax errors into StateFileParseError. */
export function parseJsonFile(text: string, what: string): unknown {
  try {
    return JSON.parse(text);
  } catch (cause) {
    throw new StateFileParseError(what, "not valid JSON");
  }
}

function parseProtocol(value: unknown): Protocol | undefined {
  if (!isString(value)) return undefined;
  return PROTOCOLS.find((protocol) => protocol === value);
}

function parseQuarantineSource(value: unknown): QuarantineSource | undefined {
  if (!isString(value)) return undefined;
  return QUARANTINE_SOURCES.find((source) => source === value);
}

function parseQuarantineReasonCode(value: unknown): QuarantineReasonCode | undefined {
  if (!isString(value)) return undefined;
  return QUARANTINE_REASON_CODES.find((code) => code === value);
}

function parseAvailability(value: unknown): Availability | undefined {
  if (!isRecord(value)) return undefined;
  if (value.kind === "unverified") return { kind: "unverified" };
  if (value.kind === "verified" && (value.liveSource === "live" || value.liveSource === "fixture")) {
    return { kind: "verified", liveSource: value.liveSource };
  }
  return undefined;
}

/** Provenance must be safe text (nonempty, control-free). */
function parseProvenance(value: unknown): string | undefined {
  if (!isSafeText(value)) return undefined;
  return value;
}

/** Parse the models.json manifest into generatedAt, provenance, availability and models. */
export function parseModelsManifest(value: unknown): {
  readonly generatedAt: string;
  readonly provenance: string;
  readonly availability: Availability;
  readonly models: readonly CatalogModel[];
} {
  if (!isRecord(value) || !isCanonicalIsoInstant(value.generatedAt) || !isUnknownArray(value.models)) {
    throw new StateFileParseError("models.json", "must be an object with a canonical generatedAt and a models array");
  }
  const provenance = parseProvenance(value.provenance);
  if (provenance === undefined) {
    throw new StateFileParseError("models.json", "must carry a nonempty provenance string");
  }
  const availability = parseAvailability(value.availability);
  if (availability === undefined) {
    throw new StateFileParseError("models.json", "must carry a valid availability marker");
  }
  const models: CatalogModel[] = [];
  const seen = new Set<string>();
  for (const entry of value.models) {
    const model = parseCatalogModel(entry);
    if (model === undefined) {
      throw new StateFileParseError("models.json", "model entry is not a valid catalog model");
    }
    if (seen.has(model.id)) {
      throw new StateFileParseError("models.json", `duplicate model id "${model.id}"`);
    }
    seen.add(model.id);
    models.push(model);
  }
  return { generatedAt: value.generatedAt, provenance, availability, models };
}

/** Parse the quarantine.json artifact. */
export function parseQuarantineFile(value: unknown): readonly QuarantineRecord[] {
  if (!isUnknownArray(value)) {
    throw new StateFileParseError("quarantine.json", "must be an array");
  }
  const records: QuarantineRecord[] = [];
  const seen = new Set<string>();
  for (const entry of value) {
    if (!isRecord(entry)) {
      throw new StateFileParseError("quarantine.json", "entry must be an object");
    }
    const id = isSafeModelId(entry.id) ? entry.id : undefined;
    const detectedAt = isCanonicalIsoInstant(entry.detectedAt) ? entry.detectedAt : undefined;
    const source = parseQuarantineSource(entry.source);
    const reasonCode = parseQuarantineReasonCode(entry.reasonCode);
    if (id === undefined || detectedAt === undefined || source === undefined || reasonCode === undefined) {
      throw new StateFileParseError("quarantine.json", "entry must carry a safe id, a canonical detectedAt, source and reasonCode");
    }
    if (seen.has(id)) {
      throw new StateFileParseError("quarantine.json", `duplicate quarantine id "${id}"`);
    }
    seen.add(id);
    records.push({ id, detectedAt, source, reasonCode });
  }
  return records;
}

/** Parse the deprecated.json artifact (grace entries plus eviction tombstones). */
export function parseDeprecatedFile(value: unknown): readonly DeprecatedEntry[] {
  if (!isUnknownArray(value)) {
    throw new StateFileParseError("deprecated.json", "must be an array");
  }
  const entries: DeprecatedEntry[] = [];
  const seen = new Set<string>();
  for (const entry of value) {
    if (!isRecord(entry)) {
      throw new StateFileParseError("deprecated.json", "entry must be an object");
    }
    const id = isSafeModelId(entry.id) ? entry.id : undefined;
    if (id === undefined || !isCanonicalIsoInstant(entry.deprecatedAt)) {
      throw new StateFileParseError("deprecated.json", "entry must carry a safe id and a canonical deprecatedAt");
    }
    const evictedAt = entry.evictedAt === undefined ? undefined : isCanonicalIsoInstant(entry.evictedAt) ? entry.evictedAt : null;
    if (evictedAt === null) {
      throw new StateFileParseError("deprecated.json", `entry ${id} has a non-canonical evictedAt`);
    }
    if (evictedAt !== undefined && Date.parse(evictedAt) <= Date.parse(entry.deprecatedAt) + FOURTEEN_DAYS_MS) {
      throw new StateFileParseError("deprecated.json", `entry ${id} evictedAt must be strictly later than deprecatedAt + 14 days`);
    }
    const model = parseCatalogModel(entry.model);
    if (model === undefined) {
      throw new StateFileParseError("deprecated.json", `entry ${id} lacks a valid frozen model`);
    }
    if (model.id !== id) {
      throw new StateFileParseError("deprecated.json", `entry id "${id}" differs from frozen model id "${model.id}"`);
    }
    if (seen.has(id)) {
      throw new StateFileParseError("deprecated.json", `duplicate deprecated id "${id}"`);
    }
    seen.add(id);
    entries.push({
      id,
      deprecatedAt: entry.deprecatedAt,
      ...(evictedAt === undefined ? {} : { evictedAt }),
      model,
    });
  }
  return entries;
}

function parseBaseUrlPatch(value: unknown): BaseUrlPatch | undefined {
  if (!isRecord(value)) {
    return undefined;
  }
  const baseUrl = parseBaseUrl(value.baseUrl);
  if (baseUrl === undefined || !isSafeText(value.evidence)) {
    return undefined;
  }
  return { baseUrl, evidence: value.evidence };
}

/** Parse the patches.json artifact; an absent map means no patches. */
export function parsePatchesFile(value: unknown): Patches {
  if (!isRecord(value)) {
    throw new StateFileParseError("patches.json", "must be an object");
  }
  const raw = value.baseUrlByProtocol;
  if (raw !== undefined && !isRecord(raw)) {
    throw new StateFileParseError("patches.json", "baseUrlByProtocol must be an object when present");
  }
  const baseUrlByProtocol: Partial<Record<Protocol, BaseUrlPatch>> = {};
  if (raw !== undefined) {
    for (const [key, patchRaw] of Object.entries(raw)) {
      const protocol = parseProtocol(key);
      if (protocol === undefined) {
        throw new StateFileParseError("patches.json", `unknown protocol key "${key}"`);
      }
      const patch = parseBaseUrlPatch(patchRaw);
      if (patch === undefined) {
        throw new StateFileParseError("patches.json", `patch for "${key}" must carry baseUrl and evidence strings`);
      }
      baseUrlByProtocol[protocol] = patch;
    }
  }
  return { baseUrlByProtocol };
}
